### ISSUE TITLE
Download button clashes with mozilla pocket button

### ISSUE THREAD

**Issue by shayp2007** [denizjcan/Firefox-Safari-15-Theme#1]

**Comment by denizjcan** [comment]
Can you add a screenshot?

If the problem is what I'm guessing, and the download button and pocket button are on the left, this problem is likely to occur because Firefox consists of two parts, one with the address bar and the other with tabs. I kept the left part with adress bar short to make more space for tabs in the single line theme. 

**There are two solutions:** 

1) You can put the download and pocket button to the right of the tabs 
![2](https://user-images.githubusercontent.com/22716602/209862505-6c6bb23c-b14c-4118-aed8-4291c824ddd1.png)

2) If you want them to be on the left, in the part with the address bar, you can give this code a greater value in **userChrome.css** and expand the space. 
For example, I changed "340px" with "440px" and it creates enough space for two buttons . You can try different values to create enough space for yourself.
![1](https://user-images.githubusercontent.com/22716602/209862514-d94dc2df-d010-49c6-a19b-5dc9f665c9c8.png)
![3](https://user-images.githubusercontent.com/22716602/209863131-fee457a9-bdf4-4edb-b502-f2c07e0cf4aa.png)

**Comment by denizjcan** [comment]
If the solutions below don't work and the problem is something else, could you add a screenshot and explanation?

If the problem is what I'm guessing, and the download button and pocket button are on the left, this problem is likely to occur because Firefox consists of two parts, one with the address bar and the other with tabs. I kept the left part with adress bar short to make more space for tabs in the single line theme. 

**There are two solutions:** 

1) You can put the download and pocket button to the right of the tabs 
![2](https://user-images.githubusercontent.com/22716602/209862505-6c6bb23c-b14c-4118-aed8-4291c824ddd1.png)

2) If you want them to be on the left, in the part with the address bar, you can give this code a greater value in **userChrome.css** and expand the space. 
For example, I changed "340px" with "440px" and it creates enough space for two buttons . You can try different values to create enough space for yourself.
![1](https://user-images.githubusercontent.com/22716602/209862514-d94dc2df-d010-49c6-a19b-5dc9f665c9c8.png)
![3](https://user-images.githubusercontent.com/22716602/209863131-fee457a9-bdf4-4edb-b502-f2c07e0cf4aa.png)
