### ISSUE TITLE
extend plugin icon cannot be remove

### ISSUE THREAD

**Issue by linitfor** [denizjcan/Firefox-Safari-15-Theme#3]
Hi Developer,

My firefox have updated to the following version. I have encounter the issue about the extend icons cannot remove.
![圖片](https://user-images.githubusercontent.com/58168507/213078594-4edb2ca9-0fc5-47ff-ac4b-dba72149a356.png)

The extend plugin icon is on the following location. Is there method to remove this icon or move this icon to other place to have better user experience.
![圖片](https://user-images.githubusercontent.com/58168507/213078790-e1ce4b11-4110-40c0-b3c7-43822ce7399c.png)

**Comment by denizjcan** [comment]
Hi Linitfor, I didn't know there was an update, thank you.   
I tried something but I don't know if it's a good idea. Can you test it and tell me your opinion?
[Test.zip](https://github.com/denizjcan/Firefox-Safari-15-Theme/files/10446598/Test.zip)
![1](https://user-images.githubusercontent.com/22716602/213181064-4486f4b0-0fb7-416a-a7cf-7db23acafe15.jpg)
I added it as an invisible button below the close button.

**Comment by linitfor** [comment]
Hi denizican,

It is really interest about your Test code. I found some new features inside. 
But I don't know the main test item about the invisible button below the close button.
I have tried and I did not saw the invisible button below the close button.

BTW. I found that you are going to let the navbar background have some other effect when the app switch to firefox.
However, this feature seem conflict to the tab colorful plugin.
(Plugin:  https://github.com/YS-Wong/Adaptive-Tab-Bar-Color ) 

On the other hand, the navbar background seem too grey. I have not study your code on detail. 
I will have an other vacation for the Chinese New Year. When I have the free time, I will study what your new idea.

I am glad to hear your news. If you have any other new testing, you can contact with me.

**Comment by denizjcan** [comment]
Hello, the button may be too low due to the screen resolution. What if we replace this icon with the shield icon in Safari instead?  
Safari:  
![1](https://user-images.githubusercontent.com/22716602/213530039-fe7bbdfc-a87f-4d61-b1ec-98ceb424c582.png)
Test (my SVG is a bit corrupted, it needs to be fixed.)
![2](https://user-images.githubusercontent.com/22716602/213530093-88aed76e-e637-4ddf-963d-8c9bfdee31f2.png)


----

I added the test code as a new theme to the download page. To use it, you have to disable the add-ons because it get its color from the Windows background. The grayness comes when the focus is gone, as in Windows File Explorer. It is imitating unfocused windows color. If you don't want to use this new color theme, the original addon compatible theme is still on the download page 😊
