### ISSUE TITLE
Tabs and caption buttons decentered

### ISSUE THREAD

**Issue by xyrirf** [denizjcan/Firefox-Safari-15-Theme#6]
I downloaded the latest version of the theme but the tabs and caption buttons are in the wrong spots.
![firefox_6q57FY1oEh](https://user-images.githubusercontent.com/123331227/213944810-1d2ec325-8e22-4260-88a7-2433004b7f48.png)
![firefox_tcmlamepsV](https://user-images.githubusercontent.com/123331227/213944811-9eda7b6a-844d-4e54-97f6-6f2d171b44bc.png)

**Comment by denizjcan** [comment]
Hello, I guess this problem has arisen because the browser header section is too narrow for some reason.  
Normally it should be this width.
![1](https://user-images.githubusercontent.com/22716602/214034114-8d690d2e-5cc7-4783-ae12-ef38a2c38376.png)

Can you tell me your screen resolution and Firefox density? Is there any chance that the now removed "Compact" option is still active and selected?
![2](https://user-images.githubusercontent.com/22716602/214034616-581cbd5b-350c-49cb-9287-00a9711364c0.png)

**Comment by xyrirf** [comment]
My screen is 1920x1080 and the density was set to compact, I just changed it to normal and now the theme works just fine, thanks for the help!

**Comment by denizjcan** [comment]
I'm glad it fixed it. Since that option is no longer available for me, I made the code according to Normal and Touch.
