### ISSUE TITLE
Is it possible to change theme based on website like safari?

### ISSUE THREAD

**Issue by dpthegrey** [denizjcan/Firefox-Safari-15-Theme#7]
Safari has this thing when you go to a website it adapts the theme to the website. It'd be cool if we can replicate that behaviour in Firefox.

**Comment by denizjcan** [comment]
Hello, this is already possible 😊. Scroll down a bit on the homepage and look at "B) Adaptive Theme 2 (According to the currently open web page)".

---

You need to install css theme in "Firefox 15 Original Theme" folder ("Firefox 15 Wallpaper Adaptive" is incompatible with this). Then, by using the "Adaptive Tab Bar Color" and "Dark Reader" add-ons together, you can have theme colors that change both according to the website and according to the dark mode.

**Comment by dpthegrey** [comment]
I managed to get it working but the back arrow is not showing and also no tab groups.. do i have to install extension for it?

**Comment by denizjcan** [comment]
Did you put the "window" folder that came in the theme to the same folder as userChrome.css? (in "Chrome" folder).  This folder contains the back button and various icons. If there is a problem with it, that's why they don't show up.

Yes, you need to install extension. Tab groups are not possible with a theme but there are nice extension in the add-ons store.

**Comment by dpthegrey** [comment]
Oh i just put the userChrome.css in chrome folder 🤓 
Alright, I'll look into extensions too. Thanks, closing the issue.
